services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - PORT=${PORT}
    ports:
      - '4002:4002'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - bookingnetwork
  
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking
      MYSQL_USER: booking
      MYSQL_PASSWORD: booking
    ports:
      - 3306:3306
    volumes:
      - booking_data:/var/lib/mysql
    networks:
      - bookingnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - bookingnetwork

volumes:
  booking_data:

networks:
  bookingnetwork:
